# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: issue_tracker_user
  password: Asad1234.
  host: localhost
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: issue_tracker
  host: localhost

production:
  adapter: mysql2
  database: defaultdb
  username: doadmin
  password: "jIvuwPsIcNe6L987"
  host: db-mysql-sgp1-80282-do-user-9830958-0.b.db.ondigitalocean.com
  pool: 5
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
